version: '3'

tasks:
  default:
    desc: "Default task - setup and run security demo"
    cmds:
      - task --list

  setup:
    desc: "Set up the Python environment"
    cmds:
      - pyenv install -s 3.12.9
      - pyenv local 3.12.9
      - poetry install
      - poetry config virtualenvs.in-project true

  generate-keys:
    desc: "Generate RSA key pair for OAuth JWT signing"
    cmds:
      - poetry run python src/generate_keys.py

  run-server:
    desc: "Run the secure MCP server"
    cmds:
      - poetry run python src/main.py
    env:
      LLM_PROVIDER: "{{.LLM_PROVIDER | default \"ollama\"}}"

  run-oauth:
    desc: "Run the OAuth authorization server"
    cmds:
      - poetry run python src/oauth_server.py

  run-openai-client:
    desc: "Run the secure OpenAI client demo"
    cmds:
      - poetry run python src/secure_clients/openai_client.py

  run-anthropic-client:
    desc: "Run the secure Anthropic client demo"
    cmds:
      - poetry run python src/secure_clients/anthropic_client.py

  run-langchain-client:
    desc: "Run the secure LangChain ReAct agent demo"
    cmds:
      - poetry run python src/secure_clients/langchain_client.py

  run-dspy-client:
    desc: "Run the secure DSPy ReAct agent demo"
    cmds:
      - poetry run python src/secure_clients/dspy_client.py

  test:
    desc: "Run all tests"
    cmds:
      - poetry run pytest tests/ -v
    env:
      LLM_PROVIDER: "{{.LLM_PROVIDER | default \"ollama\"}}"

  format:
    desc: "Format code"
    cmds:
      - poetry run black src/ tests/
      - poetry run ruff check --fix src/ tests/

  clean:
    desc: "Clean up generated files"
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf security_logs/

  generate-certs:
    desc: "Generate self-signed certificates for development"
    cmds:
      - mkdir -p certificates
      - openssl req -x509 -newkey rsa:4096 -keyout certificates/server.key -out certificates/server.crt -days 365 -nodes -subj "/CN=localhost"
      - chmod 600 certificates/server.key

  generate-trusted-certs:
    desc: "Generate locally-trusted certificates using mkcert"
    cmds:
      - ./scripts/generate-local-certs.sh

  trust-certs:
    desc: "Add current certificates to system trust store"
    cmds:
      - ./scripts/trust-self-signed.sh

  # Docker tasks
  docker-build:
    desc: "Build Docker images for all services"
    cmds:
      - docker-compose build

  docker-up:
    desc: "Start all services with Docker Compose (with TLS)"
    deps: [generate-keys, generate-certs]
    cmds:
      - docker-compose up -d

  docker-down:
    desc: "Stop all Docker services"
    cmds:
      - docker-compose down

  docker-logs:
    desc: "View logs from all Docker services"
    cmds:
      - docker-compose logs -f

  docker-restart:
    desc: "Restart all Docker services"
    cmds:
      - docker-compose restart

  docker-clean:
    desc: "Clean up Docker containers, images, and volumes"
    cmds:
      - docker-compose down -v
      - docker system prune -f

  docker-shell-oauth:
    desc: "Open shell in OAuth container"
    cmds:
      - docker-compose exec oauth /bin/bash

  docker-shell-mcp:
    desc: "Open shell in MCP container"
    cmds:
      - docker-compose exec mcp /bin/bash
